# Generated by Django 4.2.6 on 2023-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_review_delete_reviews_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
