# Generated by Django 4.2.6 on 2023-11-27 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nationalgeographic.com%2Fanimals%2Fmammals%2Ffacts%2Fdomestic-cat&psig=AOvVaw3oojcce5YHf2q2a59XaFxE&ust=1701150488806000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCICc_sa944IDFQAAAAAdAAAAABAE', upload_to=''),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='n_bought',
            field=models.IntegerField(default=0, verbose_name=django.core.validators.MinValueValidator(0)),
        ),
    ]
