# Generated by Django 4.2.6 on 2023-11-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_product_image_review_stars_alter_product_n_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='C:/Users/Sheryar/PycharmProjects/construction_site/frontend/src/assets/images/sample_product.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
