# Generated by Django 4.2.6 on 2023-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_product_image_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='n_bought',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
