# Generated by Django 4.2.6 on 2023-11-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_product_n_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
