# Generated by Django 4.2.6 on 2024-02-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0008_rename_registered_buyer_cart_buyer_and_more'),
        ('UserManagement', '0002_alter_anonymoususer_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
    ]
