# Generated by Django 4.2.6 on 2024-02-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
