# Generated by Django 4.2.6 on 2024-01-15 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_cart_created_at_cart_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
