# Generated by Django 4.2.6 on 2024-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_orderhistory_purchased_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product_discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product_image',
            field=models.ImageField(default='C:/Users/Sheryar/PycharmProjects/construction_site/frontend/src/assets/images/sample_product.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product_name',
            field=models.CharField(default='hammer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product_price',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='product_seller',
            field=models.CharField(default='talha', max_length=200),
            preserve_default=False,
        ),
    ]
