# Generated by Django 4.2.6 on 2024-02-02 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0007_remove_cart_buyer_cart_registered_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='registered_buyer',
            new_name='buyer',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='unregistered_buyer',
        ),
    ]
