# Generated by Django 4.2.6 on 2024-03-05 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0012_remove_cart_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='product_image',
            new_name='image',
        ),
    ]
